# Generated by Django 6.0.7 on 2026-07-19 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('coverage_percentage', models.IntegerField()),
                ('eligible_level', models.CharField(max_length=20)),
                ('eligible_country', models.CharField(blank=True, max_length=100)),
                ('application_deadline', models.DateField()),
                ('brochure_public_id', models.CharField(blank=True, max_length=255)),
                ('brochure_url', models.URLField(blank=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarships', to='universities.university')),
            ],
            options={
                'db_table': 'scholarship',
                'ordering': ['application_deadline', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarships.scholarship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to='accounts.user')),
            ],
            options={
                'db_table': 'scholarship_application',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['university'], name='scholarship_univers_e69193_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['eligible_country'], name='scholarship_eligibl_4b4280_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['application_deadline'], name='scholarship_applica_aaaf5d_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipapplication',
            index=models.Index(fields=['user'], name='scholarship_user_id_8df2cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='scholarshipapplication',
            constraint=models.UniqueConstraint(fields=('scholarship', 'user'), name='unique_scholarship_application'),
        ),
    ]
