# Generated by Django 6.0.7 on 2026-07-19 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='scholarships.scholarship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_scholarships', to='accounts.user')),
            ],
            options={
                'db_table': 'wishlist_scholarship',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='wishlist_sc_user_id_8b3e8f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'scholarship'), name='unique_wishlist_scholarship')],
            },
        ),
    ]
