# Generated by Django 6.0.7 on 2026-07-19 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('universities', '0001_initial'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='universities.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_universities', to='accounts.user')),
            ],
            options={
                'db_table': 'wishlist_university',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='wishlist_un_user_id_a341cf_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'university'), name='unique_wishlist_university')],
            },
        ),
    ]
