# Generated by Django 6.0.7 on 2026-07-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField()),
                ('cover_public_id', models.CharField(blank=True, max_length=255)),
                ('cover_url', models.URLField(blank=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'blog',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'faq',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'inquiries',
                'db_table': 'inquiry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField()),
                ('cover_public_id', models.CharField(blank=True, max_length=255)),
                ('cover_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'news',
                'db_table': 'news',
                'ordering': ['-published_at'],
            },
        ),
    ]
