# Generated by Django 6.0.7 on 2026-07-19 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='universities.university'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['university'], name='faculty_univers_c14ef0_idx'),
        ),
    ]
