# Generated by Django 6.0.7 on 2026-07-19 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0002_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('application_deadline', models.DateField()),
                ('start_date', models.DateField()),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to='programs.program')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='universities.university')),
            ],
            options={
                'db_table': 'intake',
                'ordering': ['start_date', 'name'],
                'indexes': [models.Index(fields=['university'], name='intake_univers_be5ef3_idx'), models.Index(fields=['program'], name='intake_program_7aeabd_idx')],
            },
        ),
    ]
