# Generated by Django 6.0.7 on 2026-07-19 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('transcript', 'Academic Transcript'), ('certificate', 'Certificate'), ('english_test', 'English Test'), ('personal_statement', 'Personal Statement'), ('resume', 'Resume'), ('other', 'Other')], max_length=30)),
                ('file_public_id', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('resource_type', models.CharField(choices=[('image', 'Image'), ('raw', 'Raw')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
            ],
            options={
                'db_table': 'application_document',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['application'], name='application_applica_83ddbd_idx')],
            },
        ),
    ]
