# Generated by Django 6.0.7 on 2026-07-19 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0002_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('misc_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='MYR', max_length=10)),
                ('bdt_equivalent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('academic_year', models.CharField(max_length=20)),
                ('pdf_public_id', models.CharField(blank=True, max_length=255)),
                ('pdf_url', models.URLField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='programs.program')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='universities.university')),
            ],
            options={
                'db_table': 'tuition_fee',
                'ordering': ['-academic_year', 'program__name'],
                'indexes': [models.Index(fields=['program'], name='tuition_fee_program_b66dad_idx'), models.Index(fields=['university'], name='tuition_fee_univers_bc3e6e_idx')],
            },
        ),
    ]
