# Generated by Django 6.0.7 on 2026-07-19 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university'),
        ),
        migrations.AddField(
            model_name='programrequirement',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='programs.program'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['university'], name='program_univers_d40e49_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['faculty'], name='program_faculty_398c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['level'], name='program_level_f24a97_idx'),
        ),
    ]
