# Generated by Django 6.0.7 on 2026-07-19 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('university_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=10)),
                ('ranking_tier', models.CharField(blank=True, max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('logo_public_id', models.CharField(blank=True, max_length=255)),
                ('logo_url', models.URLField(blank=True)),
                ('cover_public_id', models.CharField(blank=True, max_length=255)),
                ('cover_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('total_students', models.IntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.city')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.state')),
            ],
            options={
                'db_table': 'university',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_public_id', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='universities.university')),
            ],
            options={
                'db_table': 'gallery',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['state'], name='university_state_i_bfb72a_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['city'], name='university_city_id_6f5680_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['is_featured'], name='university_is_feat_eaa744_idx'),
        ),
    ]
